name: stages
title: My web site
org: ACDC
base_url: ''
myEmail: jbruel@gmail.com
profiles:
  production:
    base_url: http://jmbruel.github.io/demosite
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      branch: gh-pages
      # use master branch for <username>.github.io repository
      #branch: master
